zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  build: .
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.164.100
    KAFKA_CREATE_TOPICS: "alan-topic:1:3"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
